change-template: '* $TITLE by @$AUTHOR in (#$NUMBER)'
no-changes-template: '* No changes from last release'
include-pre-releases: false
sort-direction: ascending
categories:
  - title: 'Enhancement'
    collapse-after: 3
    labels:
      - 'enhancement'
  - title: 'Documentation'
    collapse-after: 3
    labels:
      - 'documentation'
  - title: 'Bug fix'
    collapse-after: 3
    labels:
      - 'bug'
  - title: 'Updating dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: 'Refactoring'
    collapse-after: 3
    labels:
      - 'refactoring'

template: |
  ## What has changed since $PREVIOUS_TAG
  $CHANGES

  ## Project sponsors
  @JoaoSto
